import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel='preconnect' href='https://fonts.gstatic.com'/>
        <link rel="stylesheet" href="https://use.typekit.net/xxy5clq.css?family=Acumin+Pro"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}