import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>
        <Link href="/shop">
          <a>Shop all</a>
        </Link>
      </h3>

    <Footer />
    </div>
  )
}
